//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.08 at 11:05:50 AM CET 
//


package eu.gloria.rts2.error;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for behaviour.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="behaviour">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IGNORE_ERRORS"/>
 *     &lt;enumeration value="NO_IGNORE_ERRORS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "behaviour")
@XmlEnum
public enum Behaviour {

    IGNORE_ERRORS,
    NO_IGNORE_ERRORS;

    public String value() {
        return name();
    }

    public static Behaviour fromValue(String v) {
        return valueOf(v);
    }

}
