//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.08 at 11:05:50 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gloria.eu/rts2/error")
package eu.gloria.rts2.error;
